
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pibd_orders_products
    username: your_username
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true